from aiogram import Router, F
from aiogram.types import Message, CallbackQuery, FSInputFile, InlineKeyboardMarkup, InlineKeyboardButton
from aiogram.fsm.context import FSMContext
from aiogram.fsm.state import State, StatesGroup
from aiogram.filters import StateFilter
from services.banner_service import LastPerson07_BannerService
from database.mongo import db
from loguru import logger
import asyncio

router = Router()
banner_service = LastPerson07_BannerService()

class BannerState(StatesGroup):
    """FSM states for banner creation"""
    waiting_title = State()

@router.callback_query(F.data == "create")
async def LastPerson07_create_start(callback: CallbackQuery, state: FSMContext):
    """Start banner creation"""
    try:
        await callback.answer("🎨")
        
        text = """
✍️ **Enter Banner Title**

Examples:
`Battle Through Heavens S5 E125`
`Anime Night Live Stream`
`Episode 124 - ENG SUB`

(Maximum 60 characters)
        """
        
        keyboard = InlineKeyboardMarkup(inline_keyboard=[
            [InlineKeyboardButton(text="🔥 QUICK DEMO", callback_data="demo")],
            [InlineKeyboardButton(text="🏠 MENU", callback_data="home")]
        ])
        
        await state.set_state(BannerState.waiting_title)
        await callback.message.edit_text(text, parse_mode="Markdown", reply_markup=keyboard)
        
    except Exception as e:
        logger.error(f"Create start error: {e}")
        await callback.answer("❌ Error", show_alert=True)

@router.message(StateFilter(BannerState.waiting_title))
async def LastPerson07_process_title(message: Message, state: FSMContext):
    """Process banner title from user"""
    try:
        title = message.text.strip()[:60]
        
        if len(title) < 3:
            await message.answer("❌ Title too short (minimum 3 characters)")
            return
        
        # Show loading
        status_msg = await message.answer("⚡ **Generating banner...**")
        
        try:
            banner_path = await banner_service.LastPerson07_create_banner(
                title=title,
                template_id="1"
            )
            
            # Send result
            keyboard = InlineKeyboardMarkup(inline_keyboard=[
                [InlineKeyboardButton(text="🎨 CREATE NEW", callback_data="create")],
                [InlineKeyboardButton(text="🏠 HOME", callback_data="home")]
            ])
            
            await message.answer_photo(
                photo=FSInputFile(banner_path),
                caption=f"✨ **{title}**\n\n> Generated by LastPerson07\n\n⚡ Fast & Professional",
                parse_mode="Markdown",
                reply_markup=keyboard
            )
            
            # Increment counter
            await db.LastPerson07_increment_banners(message.from_user.id)
            await db.LastPerson07_log_action(
                message.from_user.id,
                "banner_created",
                f"Title: {title}"
            )
            logger.info(f"✅ Banner created for user {message.from_user.id}: {title}")
            
        except Exception as e:
            logger.error(f"Banner generation error: {e}")
            await message.answer("❌ Generation failed. Please try again!")
        
        finally:
            try:
                await status_msg.delete()
            except:
                pass
        
        await state.clear()
        
    except Exception as e:
        logger.error(f"Process title error: {e}")
        await message.answer("❌ Error processing title")
        await state.clear()

@router.callback_query(F.data == "demo")
async def LastPerson07_demo(callback: CallbackQuery, state: FSMContext):
    """Generate demo banner"""
    try:
        await callback.answer("⚡")
        
        status = await callback.message.edit_text("⚡ **Generating demo banner...**")
        
        try:
            banner_path = await banner_service.LastPerson07_create_banner(
                title="Battle Through The Heavens Season 5",
                template_id="1"
            )
            
            keyboard = InlineKeyboardMarkup(inline_keyboard=[
                [InlineKeyboardButton(text="🎨 CREATE CUSTOM", callback_data="create")],
                [InlineKeyboardButton(text="📱 MORE TEMPLATES", callback_data="templates")],
                [InlineKeyboardButton(text="🏠 HOME", callback_data="home")]
            ])
            
            await callback.message.delete()
            await callback.message.answer_photo(
                photo=FSInputFile(banner_path),
                caption="✨ **Demo Banner**\n\n> Professional HD quality\n\nMade by LastPerson07",
                parse_mode="Markdown",
                reply_markup=keyboard
            )
            
            logger.info(f"✅ Demo created for user {callback.from_user.id}")
            
        except Exception as e:
            logger.error(f"Demo error: {e}")
            await callback.message.edit_text("❌ Demo generation failed. Try again!")
        
        await state.clear()
        
    except Exception as e:
        logger.error(f"Demo callback error: {e}")
        await callback.answer("❌ Error", show_alert=True)

@router.callback_query(F.data.startswith("template:"))
async def LastPerson07_select_template(callback: CallbackQuery, state: FSMContext):
    """Select specific template"""
    try:
        template_id = callback.data.split(":")[1]
        await state.update_data(template_id=template_id)
        await state.set_state(BannerState.waiting_title)
        
        await callback.answer("✍️")
        
        kb = InlineKeyboardMarkup(inline_keyboard=[
            [InlineKeyboardButton(text="🔥 QUICK DEMO", callback_data="demo")],
            [InlineKeyboardButton(text="🏠 MENU", callback_data="home")]
        ])
        
        text = f"""
✍️ **Enter Banner Title for Template {template_id}**

(Maximum 60 characters)
        """
        
        await callback.message.edit_text(text, parse_mode="Markdown", reply_markup=kb)
        
    except Exception as e:
        logger.error(f"Template select error: {e}")
        await callback.answer("❌ Error", show_alert=True)
